name: yousentech_pos_invoice_printing
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.6.0
  flutter_screenutil: ^5.9.3

  pos_shared_preferences:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_shared_preferences.git
      ref: master
  shared_widgets:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_shared_widgets.git
      ref: master
  yousentech_pos_payment:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_payment.git
      ref: master
  yousentech_pos_payment_summary:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_payment_summary.git
      ref: master
  yousentech_pos_invoice:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_invoice.git
      ref: master
  yousentech_pos_messaging:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_messaging.git
      ref: master
  yousentech_pos_printing:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_printing.git
      ref: master
  yousentech_pos_local_db:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_local_db.git
      ref: master
  ysn_pos_android_printer:
    git:
      url: https://github.com/YousenTech-Flutter/ysn_pos_android_printer.git
      ref: main
  path_provider: ^2.1.5
  barcode_widget: ^2.0.4
  screenshot: ^3.0.0
  flutter_bluetooth_printer: ^2.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  network_info_plus: ^4.0.2
  fl_chart: ^0.69.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ARIALBD
      fonts:
        - asset: assets/fonts/ARIALBD.TTF
    - family: ARIALBD
      fonts:
        - asset: assets/fonts/ARIAL.TTF
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
